### ISSUE TITLE
[Question] Best strategy for converting Data.Text.Lazy into Data.Text

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Dhall-Library#12]
`Dhall` exposes `Data.Text.Lazy` as `Text` while most haskell modules (and prelude) will use the strict version by default.

1. What would be the best strategy to hide the conversion boiler plate ? 
2. Why is `dhall` defaulting to the lazy version while - for most configuration purpose - I would expect  most 'string' to be kind of short.

Thanks for your help

**Comment by Gabriel439** [comment]
Yeah, I'm fine with switching to strict `Text`.  The use of lazy `Text` is an artifact of `dhall` originally being based on `morte`, which used to use lazy `Text` for lazy parsing.  However, now that `dhall` uses `trifecta` for parsing there's really no point using lazy `Text` any longer

**Comment by Gabriel439** [comment]
Actually, on second thought I will probably keep using lazy `Text`.  While working on this I realized that lazy `Text` is more advantageous for two reasons:

* You can read input lazily by using lazy `Text`
* You can also stream output lazily such as the output from this program:

```
let replicate = https://ipfs.io/ipfs/QmcTbCdS21pCxXysTzEiucDuwwLWbLUWNSKwkJVfwpy2zK/Prelude/List/replicate
in  replicate +1000000 Text "ABC"
```

However, I still kept the conversion to strict `Text` in the following branch:

https://github.com/Gabriel439/Haskell-Dhall-Library/tree/gabriel/strict_test

... so that if I ever change my mind I can go back to that

**Comment by PierreR** [comment]
I am just the challenger here but isn't this article suggesting otherwise:
http://www.snoyman.com/blog/2016/12/beware-of-readfile

**Comment by Gabriel439** [comment]
So I can adapt the `trifecta` `Parser` to consume `Text` from a streaming library, but there is still the issue of streaming output

**Comment by Gabriel439** [comment]
I will go ahead and close this since it's unlikely that I will switch to strict `Text`
