### ISSUE TITLE
Question: How to remove duplicate elements in a List of Text

### ISSUE THREAD

**Issue by scott-fleischman** [Gabriel439/Haskell-Dhall-Library#72]
Is there a way to remove duplicate elements in a List of Text?

Consider the following code. You can interpret the List (List Text) as a list of dependencies each with their transitive dependencies. How can we combine the lists while removing duplicate elements in the result?

```
let concat = https://ipfs.io/ipfs/Qmbh2ifwcpX9a384vJMehySbV7rdvYhzVbL5ySs84k8BgY/Prelude/List/concat
in concat Text
[ [ "abc", "def" ]
, [ "abc", "ghi" ]
]
```

The only way I can think of accomplishing this is to have a convention where you associate a string like "abc" with a canonical numeric representation ("abc" is 0, "def" is 1, etc.) and make sure you maintain those associations throughout the code. Then you can remove entries that have a matching canonical number. However, that seems pretty tedious and error prone since it relies on coding discipline to accomplish.

Is there a better way to achieve this?

Thanks!

**Comment by Gabriel439** [comment]
There is definitely not a way to do this in `dhall`, mainly because I intentionally do not support comparing `Text` values for equality.  From `dhall`'s perspective a `Text` value is an opaque blob that you can only concatenate and that is it.

If `dhall` were to support the ability to remove duplicates then you would be able to implement an equality test for `Text` by storing two `Text` values in a 2-element list, removing duplicates, and then testing the length of the resulting list.

The main reason for forbidding `Text` equality comparisons is to prevent people from parsing `Text` values at all, in order to encourage them to use more structured data types instead.

I don't think there will be a very efficient and idiomatic way to do this in Dhall, and I think the more appropriate solution here is to marshal the configuration into Haskell using Dhall's Haskell integration and do the remaining processing there.  Dhall was never intended to be a fully featured programming language and manipulating graphs is definitely out of scope for Dhall.

However, I'll still try to see if there is a way to do this in Dhall, even if it is grossly inefficient just to see how far we can get.

First, what is the reason that you need each dependency to be unique?  There might be a solution to this problem that does not require uniqueness in the first place.

Second, if we do go with the natural number approach you suggested, you actually don't need coding discipline to ensure that the `Natural` values that you tag dependencies with are unique.  Assuming that you have a starting list of unique paths in your graph of type:

```haskell
uniquePaths : List Text
```

... then you can ensure that each dependency is tagged with a unique `Natural` number using `List/indexed`:

```haskell
List/indexed Text uniquePaths : List { index : Natural, value : Text }
```

**Comment by Gabriel439** [comment]
I'll go ahead and close this for now since I believe the original question was answered.  Feel free to reopen if there is more you would like to discuss

**Comment by scott-fleischman** [comment]
Thanks. Yes the main question is answered, so closing the issue is fine. Mainly I was confirming what I suspected to be the case, and seeing what the boundaries of using Dhall would be.

One final observation. An advantage to having a function that removes duplicates is that you don't have to specify a canonical list of dependencies initially--it can be computed from the dependency lists. But as you say that probably isn't the right choice to do in Dhall.

**Comment by kim366** [comment]
Now I am confused. I'm probably missing the point of Dhall, but my use case is switching out environment modules based on an environment variable. So for me Dhall does not fulfil the purpose of being a configuration language. What are my options?
